### ISSUE TITLE
Prebuilt JS

### ISSUE THREAD

**Issue by bisubus** [bendrucker/angular-q-promisify#2]
Can prebuilt (UMD) script be added to `dist`, please? Publishing it to Bower would be also great, but it isn't crucial.

Amazing job on this $q decorator, but it is too environment-dependent to be usable right out of the box in random conditions.

**Comment by bendrucker** [comment]
Sorry, can't do that across all my projects. https://wzrd.in/ is ideal for this -- just download from there and commit if you don't want to use Browserify/Webpack.

**Comment by bisubus** [comment]
Awesome service indeed, thanks for recommending it.

**Comment by bendrucker** [comment]
It's a bit slow at times so definitely don't directly link, even though it caches
